name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Generate API
        run: |
          ./gradlew -PnewVersion=$GITHUB_REF_NAME generateOpenApiClient 
          ./gradlew -PnewVersion=$GITHUB_REF_NAME copyGeneratedSources 
          ./gradlew -PnewVersion=$GITHUB_REF_NAME build 
          ./gradlew -PnewVersion=$GITHUB_REF_NAME publish
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}